{
 "title": "Aula",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de requisições no período",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(aula_requests_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usuários logados",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aula_usuarios_logados_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(aula_request_duration_seconds_bucket[1m]))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, rate(aula_request_duration_seconds_bucket[1m]))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99, rate(aula_request_duration_seconds_bucket[1m]))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "request/segundo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(aula_requests_total[1m]))",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Taxa de erro da API",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(aula_requests_total{statusCode=\"500\"}[1m])) / sum(rate(aula_requests_total[1m]))",
     "legendFormat": "Taxa de erro"
    }
   ]
  }
 ]
}